### PR TITLE
Added Error Handling on ED Log Path

### PR DESCRIPTION
**Pull request by spreedated**
.gitignore
---
+ Added WINDOWS enviroment to be handled

EDGPS
---
+ Added Error handling on ED Log path input from user
+ If user Log path seems correct (checks if *.log files are actually there), path is saved to TXT file for later use
+ Reuse of saved path on startup

TBD:
Acutal user-settings file for future use of common-settings from users, like an INI.

### CODE REVIEW

**Comment by spreedated** [comment]
Also NOTE: this is very basic, but provide some better user experience.

**Comment by ComputerMaster1st** [comment]
https://github.com/ComputerMaster1st/Elite-Dangerous-Galactic-Positioning-System/blob/master/Core/Parser.cs#L9 << I think this should be used when sanitising the directory path. ;)

**Comment by spreedated** [comment]
I've adpoted some of your previous code, you may delete those line which "sanitize" the path.
However the "Path" function sanitize it by itself, if the path includes illegal chars and/or is simply invalid in it's format it throws an error, this error should be handled. So there's no need to niptuck the userinput.

**Comment by ComputerMaster1st** [comment]
Oke, I'll go ahead & merge it :)

**Pull request merged**
